<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>VacuumCleaner</AssemblyName>
    <RootNamespace>VacuumCleaner</RootNamespace>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="YamlDotNet" Version="11.2.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(EXILED_REFERENCES)\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(EXILED_REFERENCES)\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>$(EXILED_REFERENCES)\Assembly-CSharp-firstpass.dll</HintPath>
    </Reference>
    <Reference Include="AudioPlayerApi">
      <HintPath>$(EXILED_REFERENCES)\AudioPlayerApi.dll</HintPath>
    </Reference>
    <Reference Include="CommandSystem.Core">
      <HintPath>$(EXILED_REFERENCES)\CommandSystem.Core.dll</HintPath>
    </Reference>
    <Reference Include="Exiled.API">
      <HintPath>$(EXILED_REFERENCES)\Exiled.API.dll</HintPath>
    </Reference>
    <Reference Include="Exiled.CreditTags">
      <HintPath>$(EXILED_REFERENCES)\Exiled.CreditTags.dll</HintPath>
    </Reference>
    <Reference Include="Exiled.CustomItems">
      <HintPath>$(EXILED_REFERENCES)\Exiled.CustomItems.dll</HintPath>
    </Reference>
    <Reference Include="Exiled.CustomRoles">
      <HintPath>$(EXILED_REFERENCES)\Exiled.CustomRoles.dll</HintPath>
    </Reference>
    <Reference Include="Exiled.Events">
      <HintPath>$(EXILED_REFERENCES)\Exiled.Events.dll</HintPath>
    </Reference>
    <Reference Include="Exiled.Loader">
      <HintPath>$(EXILED_REFERENCES)\Exiled.Loader.dll</HintPath>
    </Reference>
    <Reference Include="Exiled.Permissions">
      <HintPath>$(EXILED_REFERENCES)\Exiled.Permissions.dll</HintPath>
    </Reference>
    <Reference Include="HintServiceMeow">
      <HintPath>$(EXILED_REFERENCES)\HintServiceMeow-Exiled.dll</HintPath>
    </Reference>
    <Reference Include="LabApi">
      <HintPath>$(EXILED_REFERENCES)\LabApi.dll</HintPath>
    </Reference>
    <Reference Include="Mirror">
      <HintPath>$(EXILED_REFERENCES)\Mirror.dll</HintPath>
    </Reference>
    <Reference Include="NorthwoodLib">
      <HintPath>$(EXILED_REFERENCES)\NorthwoodLib.dll</HintPath>
    </Reference>
    <Reference Include="Pooling">
      <HintPath>$(EXILED_REFERENCES)\Pooling.dll</HintPath>
    </Reference>
    <Reference Include="ProjectMER">
      <HintPath>$(EXILED_REFERENCES)\ProjectMER.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(EXILED_REFERENCES)\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(EXILED_REFERENCES)\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(EXILED_REFERENCES)\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(EXILED_REFERENCES)\Newtonsoft.Json.dll</HintPath>
    </Reference>
     
  </ItemGroup>

</Project>